function tStyle = GetStylemark()
styleID = 1;
tStyle(styleID).color = '-bv'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'r'; tStyle(styleID).MarkerSize = 8; 
tStyle(styleID).scolor = 'b';
styleID = styleID + 1;
tStyle(styleID).color = ':gs'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'k'; tStyle(styleID).MarkerSize = 8; 
tStyle(styleID).scolor = 'g';
styleID = styleID + 1;
tStyle(styleID).color = '-r+'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'r'; tStyle(styleID).MarkerSize = 8; 
tStyle(styleID).scolor = 'r';
styleID = styleID + 1;
tStyle(styleID).color = '-cd'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'k'; tStyle(styleID).MarkerSize = 8; 
tStyle(styleID).scolor = 'c';
styleID = styleID + 1;
tStyle(styleID).color = '-mo'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'k'; tStyle(styleID).MarkerSize = 8; 
tStyle(styleID).scolor = 'm';
styleID = styleID + 1;
tStyle(styleID).color = '-y*'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'k'; tStyle(styleID).MarkerSize = 8; 
tStyle(styleID).scolor = 'y';
styleID = styleID + 1;
tStyle(styleID).color = '-kh'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'k'; tStyle(styleID).MarkerSize = 8; 
styleID = styleID + 1;
tStyle(styleID).scolor = 'k';
% styleID = 1;
% tStyle(styleID).color = '-k'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'y'; tStyle(styleID).MarkerSize = 8; 
% styleID = styleID + 1;
% tStyle(styleID).color = '-rv'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'r'; tStyle(styleID).MarkerSize = 8; 
% styleID = styleID + 1;
% tStyle(styleID).color = ':bs'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'k'; tStyle(styleID).MarkerSize = 8; 
% styleID = styleID + 1;
% tStyle(styleID).color = '-m'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'y'; tStyle(styleID).MarkerSize = 8; 
% styleID = styleID + 1;
% tStyle(styleID).color = '-b+'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'r'; tStyle(styleID).MarkerSize = 8; 
% styleID = styleID + 1;
% tStyle(styleID).color = '-rd'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'k'; tStyle(styleID).MarkerSize = 8; 
% styleID = styleID + 1;
% tStyle(styleID).color = '-.b'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'b'; tStyle(styleID).MarkerSize = 8; 
% styleID = styleID + 1;
% tStyle(styleID).color = '--k'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'b'; tStyle(styleID).MarkerSize = 10; 
% styleID = styleID + 1;
% tStyle(styleID).color = '-kv'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'r'; tStyle(styleID).MarkerSize = 10; 
% styleID = styleID + 1;
% tStyle(styleID).color = ':ks'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'k'; tStyle(styleID).MarkerSize = 10; 
% styleID = styleID + 1;
% tStyle(styleID).color = ':k'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'y'; tStyle(styleID).MarkerSize = 10; 
% styleID = styleID + 1;
% tStyle(styleID).color = '-.k+'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'r'; tStyle(styleID).MarkerSize = 10; 
% styleID = styleID + 1;
% tStyle(styleID).color = '-.kd'; tStyle(styleID).LineWidth = 2; tStyle(styleID).MarkerFaceColor = 'k'; tStyle(styleID).MarkerSize = 10; 