function tStyle = GetNomarkStyle()
% style array
% color style
styleID = 1;
tStyle(styleID).color = '-b'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'b';
styleID = styleID + 1;
tStyle(styleID).color = '-g'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'g';
styleID = styleID + 1;
tStyle(styleID).color = '-r'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'r';
styleID = styleID + 1;
tStyle(styleID).color = '-k'; tStyle(styleID).LineWidth = 1;
tStyle(styleID).scolor = 'k';
styleID = styleID + 1;
tStyle(styleID).color = '-c'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'c';
styleID = styleID + 1;
tStyle(styleID).color = '-m'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'm';
styleID = styleID + 1;
tStyle(styleID).color = '-y'; tStyle(styleID).LineWidth = 1;
tStyle(styleID).scolor = 'y';
styleID = styleID + 1;
tStyle(styleID).color = '-w'; tStyle(styleID).LineWidth = 1;
tStyle(styleID).scolor = 'w';
styleID = styleID + 1;
tStyle(styleID).color = '--b'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'b';
styleID = styleID + 1;
tStyle(styleID).color = '--g'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'g';
styleID = styleID + 1;
tStyle(styleID).color = '--r'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'r';
styleID = styleID + 1;
tStyle(styleID).color = '--c'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'c';
styleID = styleID + 1;
tStyle(styleID).color = '--m'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'm';
styleID = styleID + 1;
tStyle(styleID).color = '--y'; tStyle(styleID).LineWidth = 1;
tStyle(styleID).scolor = 'y';
styleID = styleID + 1;
tStyle(styleID).color = '--k'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'k';
styleID = styleID + 1;
tStyle(styleID).color = '--w'; tStyle(styleID).LineWidth = 1;
tStyle(styleID).scolor = 'w';
styleID = styleID + 1;
tStyle(styleID).color = '-.b'; tStyle(styleID).LineWidth = 1;
tStyle(styleID).scolor = 'b';
styleID = styleID + 1;
tStyle(styleID).color = '-.g'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'g';
styleID = styleID + 1;
tStyle(styleID).color = '-.r'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'r';
styleID = styleID + 1;
tStyle(styleID).color = '-.c'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'c';
styleID = styleID + 1;
tStyle(styleID).color = '-.m'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'm';
styleID = styleID + 1;
tStyle(styleID).color = '-.y'; tStyle(styleID).LineWidth = 1;
tStyle(styleID).scolor = 'y';
styleID = styleID + 1;
tStyle(styleID).color = '-.k'; tStyle(styleID).LineWidth = 1; 
tStyle(styleID).scolor = 'k';
styleID = styleID + 1;
tStyle(styleID).color = '-.w'; tStyle(styleID).LineWidth = 1;
tStyle(styleID).scolor = 'w';